import {CeoMessage,ContactInfo} from '../../components/BrandContent';
export const metadata = {title:'회사소개 | 와이플랜 Y-PLAN',description:'브랜드를 이해하는 전략부터 실행과 개선까지. 와이플랜의 생각과 일하는 방식을 소개합니다.'};
export default function Company() {return <main className="inner-page company-page">
  <section className="inner-hero section-dark"><div className="breadcrumb"><a href="/">HOME</a><span>COMPANY</span></div><p className="eyebrow">WHY YOUR BRAND NEEDS A PLAN.</p><h1>당신의 브랜드를 이해하고,<br/><span>다음을 함께 계획합니다.</span></h1><div className="inner-hero-bottom"><p>와이플랜은 온라인 마케팅과 콘텐츠 제작,<br/>비즈니스 컨설팅을 연결하는 브랜드 파트너입니다.</p><span>ABOUT Y-PLAN</span></div></section>
  <section className="about section-light"><div className="section-label"><span>01 — OUR PERSPECTIVE</span><span>우리가 바라보는 마케팅</span></div><div className="company-story"><h2>같은 광고도,<br/><span>브랜드에 따라 달라야 합니다.</span></h2><div><p>브랜드마다 출발점이 다릅니다.<br/>고객도, 강점도, 지금 해결해야 할 고민도 다릅니다.</p><p>와이플랜은 먼저 브랜드를 듣고 이해합니다. 필요한 채널과 콘텐츠를 선별하고, 목표에 맞는 실행의 순서를 정리합니다.</p><p>좋은 계획이 실행으로 이어지고, 실행에서 발견한 정보가 다시 다음 계획으로 이어지도록 함께합니다.</p></div></div></section>
  <CeoMessage />
  <section className="company-values section-dark"><div className="section-label"><span>02 — WHAT WE BELIEVE</span><span>와이플랜의 기준</span></div><div className="value-row"><span>01 / UNDERSTAND</span><h3>먼저 이해합니다.</h3><p>업종과 고객, 브랜드의 강점을 살핍니다. 정해진 해답보다 지금 필요한 질문에서 시작합니다.</p></div><div className="value-row"><span>02 / CONNECT</span><h3>하나의 방향으로 연결합니다.</h3><p>검색, 콘텐츠, 디자인과 홍보가 같은 메시지를 전하도록 필요한 접점을 연결합니다.</p></div><div className="value-row"><span>03 / IMPROVE</span><h3>다음 실행을 함께 정합니다.</h3><p>진행 현황과 반응을 공유합니다. 실행에서 배운 내용을 바탕으로 다음 방향을 조정합니다.</p></div></section>
  <section className="about section-light"><div className="section-label"><span>03 — OUR CAPABILITIES</span><span>함께할 수 있는 일</span></div><div className="section-intro"><h2>마케팅에서 제작까지,<br/><span>사업의 다음을 위한 연결.</span></h2><p>필요한 서비스부터 시작할 수 있습니다.<br/>브랜드의 상황에 맞는 조합을 함께 찾습니다.</p></div><div className="company-capabilities"><a href="/services#search"><span>01</span><h3>검색·발견</h3><p>브랜드블로그 · 플레이스 · 유튜브</p></a><a href="/services#social"><span>02</span><h3>광고·커뮤니티</h3><p>영상 광고 · 체험단 · 샤오홍슈</p></a><a href="/services#pr"><span>03</span><h3>리뷰·언론</h3><p>리뷰 콘텐츠 · 언론사 송출</p></a><a href="/services#creative"><span>04</span><h3>콘텐츠·제작</h3><p>영상 · 사진 · 디자인 · 홈페이지</p></a><a href="/services#business"><span>05</span><h3>비즈니스 컨설팅</h3><p>할랄인증 · 프랜차이즈 · 정책자금</p></a></div></section>
  <section className="detail-section section-dark"><div className="section-label"><span>OUR CLIENTS</span><span>함께 고민하는 업종</span></div><h2>업종을 이해하면,<br/><span>전략이 달라집니다.</span></h2><p className="industry-intro">음식점, 병원, 쇼핑몰, 프랜차이즈와 소상공인까지. 고객이 브랜드를 찾고 선택하는 과정을 살피며 업종과 상황에 맞는 방향을 제안합니다.</p><div className="industry-tags"><span>음식점 · 로컬 매장</span><span>병원 · 전문 서비스</span><span>쇼핑몰 · 제품 브랜드</span><span>프랜차이즈</span><span>소상공인 · 창업 기업</span></div><ContactInfo /></section>
  <section className="page-cta"><p className="eyebrow">YOUR NEXT, OUR PLAN</p><h2>브랜드의 고민에서,<br/>함께할 계획으로.</h2><p>현재 상황과 원하는 방향을 이야기해 주세요.</p><a className="button" href="/#contact">와이플랜에 상담하기</a></section>
</main>;}
